steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/render-svc:latest
      - -f
      - render-svc/Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    args: [push, gcr.io/$PROJECT_ID/render-svc:latest]
images:
  - gcr.io/$PROJECT_ID/render-svc:latest
options:
  logging: CLOUD_LOGGING_ONLY
